# Generated by Django 4.2.2 on 2023-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_rename_parking_id_booking_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
